/* MASTER */

CREATE TABLE IN_SUPPLIER
(
	SUPPLIER_ID BIGINT IDENTITY(1,1) NOT NULL,
	SUPPLIER_CODE BIGINT NOT NULL,
	SUPPLIER_NAME NVARCHAR(200) NOT NULL,
	SUPPLIER_EMAIL NVARCHAR(200) NULL,
	SUPPLIER_CONTACT_PERSON NVARCHAR(200) NULL,
	SUPPLIER_PHONE_NO NVARCHAR(20) NULL,
	SUPPLIER_FAX_NO NVARCHAR(20) NULL,
	SUPPLIER_ADDRESS NVARCHAR(500) NULL,
	SUPPLIER_DESCRIPTION NVARCHAR(1000) NULL,
	ACTIVE BIT NULL,
	CONSTRAINT [PK_IN_SUPPLIER] PRIMARY KEY CLUSTERED 
	(
		SUPPLIER_ID ASC
	)
)

CREATE TABLE IN_MATERIAL
(
	MATERIAL_ID BIGINT IDENTITY(1,1) NOT NULL,
	MATERIAL_CODE BIGINT NOT NULL,
	MATERIAL_NAME NVARCHAR(200) NOT NULL,
	MATERIAL_DESCRIPTION NVARCHAR(100) NULL,
	UOM_ID_RECEIVE BIGINT NOT NULL,
	UOM_ID_COUNT BIGINT NOT NULL,
	UOM_ID_USE BIGINT NOT NULL,
	ACTIVE BIT NULL,
	CONSTRAINT [PK_IN_MATERIAL] PRIMARY KEY CLUSTERED 
	(
		MATERIAL_ID ASC
	)
)

CREATE TABLE IN_WAREHOUSE
(
	WAREHOUSE_ID BIGINT IDENTITY(1,1) NOT NULL,
	BRANCH_ID BIGINT NOT NULL,
	WAREHOUSE_CODE NVARCHAR(100) NOT NULL,
	WAREHOUSE_NAME BIGINT NOT NULL,
	WAREHOUSE_DESCRIPTION BIGINT NULL,
	ACTIVE BIT NULL,
	CONSTRAINT [PK_IN_WAREHOUSE] PRIMARY KEY CLUSTERED 
	(
		WAREHOUSE_ID ASC
	)
)

CREATE TABLE IN_BILL_OF_MATERIAL_GROUP
(
	BILL_OF_MATERIAL_GROUP_ID BIGINT IDENTITY(1,1) NOT NULL,
	BILL_OF_MATERIAL_GROUP_CODE BIGINT NOT NULL,
	BILL_OF_MATERIAL_GROUP_NAME NVARCHAR(200) NOT NULL,
	BILL_OF_MATERIAL_GROUP_DESCRIPTION NVARCHAR(100) NULL,
	CONSTRAINT [PK_IN_BILL_OF_MATERIAL_GROUP] PRIMARY KEY CLUSTERED 
	(
		BILL_OF_MATERIAL_GROUP_ID ASC
	)
)

CREATE TABLE IN_BILL_OF_MATERIAL_HEAD
(
	BILL_OF_MATERIAL_HEAD_ID BIGINT IDENTITY(1,1) NOT NULL,
	BILL_OF_MATERIAL_GROUP_ID BIGINT NOT NULL,
	BILL_OF_MATERIAL_HEAD_CODE BIGINT NOT NULL,
	BILL_OF_MATERIAL_HEAD_NAME NVARCHAR(200) NOT NULL,
	BILL_OF_MATERIAL_HEAD_DESCRIPTION NVARCHAR(100) NULL,
	CONSTRAINT [PK_IN_BILL_OF_MATERIAL_HEAD] PRIMARY KEY CLUSTERED 
	(
		BILL_OF_MATERIAL_HEAD_ID ASC
	)
)

CREATE TABLE IN_BILL_OF_MATERIAL_DETAIL
(
	BILL_OF_MATERIAL_DETAIL_ID BIGINT IDENTITY(1,1) NOT NULL,
	BILL_OF_MATERIAL_HEAD_ID BIGINT NOT NULL,
	MATERIAL_ID BIGINT NULL,
	BILL_OF_MATERIAL_HEAD_ID_SUB BIGINT NOT NULL,
	AMOUNT NUMERIC(11,4) NOT NULL,
	LOST_FACTOR TINYINT NOT NULL, 
	CONSTRAINT [PK_IN_BILL_OF_MATERIAL_DETAIL] PRIMARY KEY CLUSTERED 
	(
		BILL_OF_MATERIAL_DETAIL_ID ASC
	)
)

ALTER TABLE IN_MATERIAL
ADD CONSTRAINT FK_IN_MATERIAL_DB_UOM_RECEIVE 
FOREIGN KEY (UOM_ID_RECEIVE) REFERENCES DB_UOM (UOM_ID)

ALTER TABLE IN_MATERIAL
ADD CONSTRAINT FK_IN_MATERIAL_DB_UOM_COUNT
FOREIGN KEY (UOM_ID_COUNT) REFERENCES DB_UOM (UOM_ID)

ALTER TABLE IN_MATERIAL
ADD CONSTRAINT FK_IN_MATERIAL_DB_UOM_USE
FOREIGN KEY (UOM_ID_USE) REFERENCES DB_UOM (UOM_ID)
	
ALTER TABLE IN_WAREHOUSE
ADD CONSTRAINT FK_IN_WAREHOUSE_DB_BRANCH
FOREIGN KEY (BRANCH_ID) REFERENCES DB_BRANCH (BRANCH_ID)
		
ALTER TABLE IN_BILL_OF_MATERIAL_HEAD
ADD CONSTRAINT FK_IN_BILL_OF_MATERIAL_HEAD_IN_BILL_OF_MATERIAL_GROUP
FOREIGN KEY (BILL_OF_MATERIAL_GROUP_ID) REFERENCES IN_BILL_OF_MATERIAL_GROUP (BILL_OF_MATERIAL_GROUP_ID)
	
ALTER TABLE IN_BILL_OF_MATERIAL_DETAIL
ADD CONSTRAINT FK_IN_BILL_OF_MATERIAL_DETAIL_IN_BILL_OF_MATERIAL_HEAD
FOREIGN KEY (BILL_OF_MATERIAL_HEAD_ID) REFERENCES IN_BILL_OF_MATERIAL_HEAD (BILL_OF_MATERIAL_HEAD_ID)

ALTER TABLE IN_BILL_OF_MATERIAL_DETAIL
ADD CONSTRAINT FK_IN_BILL_OF_MATERIAL_DETAIL_IN_MATERIAL
FOREIGN KEY (MATERIAL_ID) REFERENCES IN_MATERIAL (MATERIAL_ID)
	
ALTER TABLE IN_BILL_OF_MATERIAL_DETAIL
ADD CONSTRAINT FK_IN_BILL_OF_MATERIAL_DETAIL_IN_BILL_OF_MATERIAL_HEAD_SUB
FOREIGN KEY (BILL_OF_MATERIAL_HEAD_ID_SUB) REFERENCES IN_BILL_OF_MATERIAL_HEAD (BILL_OF_MATERIAL_HEAD_ID)

/* TRANSACTION */

CREATE TABLE IN_RECEIVE_MATERIAL_HEAD
(
	RECEIVE_MATERIAL_HEAD_ID BIGINT IDENTITY(1,1) NOT NULL,
	SUPPLIER_ID BIGINT NULL,
	WAREHOUSE_ID_SOURCE BIGINT NULL,
	OTHER_SOURCE NVARCHAR(1000) NULL,
	REFERENCE_NO NVARCHAR(100) NOT NULL,
	TRANSACTION_NO NVARCHAR(10) NOT NULL,
	TRANSACTION_DATE DATETIME NOT NULL,
	TRANSACTION_STATUS BIGINT NOT NULL,
	REASON_ID BIGINT NOT NULL,
	CONSTRAINT [PK_IN_RECEIVE_MATERIAL_HEAD] PRIMARY KEY CLUSTERED 
	(
		RECEIVE_MATERIAL_HEAD_ID ASC
	)
)

CREATE TABLE IN_RECEIVE_MATERIAL_DETAIL
(
	RECEIVE_MATERIAL_DETAIL_ID BIGINT IDENTITY(1,1) NOT NULL,
	RECEIVE_MATERIAL_HEAD_ID BIGINT NOT NULL,
	MATERIAL_ID BIGINT NOT NULL,
	WAREHOUSE_ID_DESTINATION BIGINT NOT NULL,
	CONSTRAINT [PK_IN_RECEIVE_MATERIAL_DETAIL] PRIMARY KEY CLUSTERED 
	(
		RECEIVE_MATERIAL_DETAIL_ID ASC
	)
)

CREATE TABLE IN_SEND_MATERIAL_HEAD
(
	SEND_MATERIAL_HEAD_ID BIGINT IDENTITY(1,1) NOT NULL,
	TRANSACTION_NO NVARCHAR(10) NOT NULL,
	TRANSACTION_DATE DATETIME NOT NULL,
	TRANSACTION_STATUS BIGINT NOT NULL,
	REASON_ID BIGINT NOT NULL,
	CONSTRAINT [PK_IN_SEND_MATERIAL_HEAD] PRIMARY KEY CLUSTERED 
	(
		SEND_MATERIAL_HEAD_ID ASC
	)
)

CREATE TABLE IN_SEND_MATERIAL_DETAIL
(
	SEND_MATERIAL_DETAIL_ID BIGINT IDENTITY(1,1) NOT NULL,
	SEND_MATERIAL_HEAD_ID BIGINT NOT NULL,
	WAREHOUSE_ID_SOURCE BIGINT NOT NULL,
	MATERIAL_ID BIGINT NOT NULL,
	WAREHOUSE_ID_DESTINATION BIGINT NOT NULL,
	CONSTRAINT [PK_IN_SEND_MATERIAL_DETAIL] PRIMARY KEY CLUSTERED 
	(
		SEND_MATERIAL_DETAIL_ID ASC
	)
)

ALTER TABLE IN_RECEIVE_MATERIAL_HEAD
ADD CONSTRAINT FK_IN_RECEIVE_MATERIAL_HEAD_IN_SUPPLIER
FOREIGN KEY (SUPPLIER_ID) REFERENCES IN_SUPPLIER (SUPPLIER_ID)

ALTER TABLE IN_RECEIVE_MATERIAL_HEAD
ADD CONSTRAINT FK_IN_RECEIVE_MATERIAL_HEAD_IN_WAREHOUSE
FOREIGN KEY (WAREHOUSE_ID_SOURCE) REFERENCES IN_WAREHOUSE (WAREHOUSE_ID)

ALTER TABLE IN_RECEIVE_MATERIAL_HEAD
ADD CONSTRAINT FK_IN_RECEIVE_MATERIAL_HEAD_DB_REASON
FOREIGN KEY (REASON_ID) REFERENCES DB_REASON (REASON_ID)

ALTER TABLE IN_RECEIVE_MATERIAL_DETAIL
ADD CONSTRAINT FK_IN_RECEIVE_MATERIAL_DETAIL_IN_RECEIVE_MATERIAL_HEAD
FOREIGN KEY (RECEIVE_MATERIAL_HEAD_ID) REFERENCES IN_RECEIVE_MATERIAL_HEAD (RECEIVE_MATERIAL_HEAD_ID)

ALTER TABLE IN_RECEIVE_MATERIAL_DETAIL
ADD CONSTRAINT FK_IN_RECEIVE_MATERIAL_DETAIL_IN_MATERIAL
FOREIGN KEY (MATERIAL_ID) REFERENCES IN_MATERIAL (MATERIAL_ID)

ALTER TABLE IN_RECEIVE_MATERIAL_DETAIL
ADD CONSTRAINT FK_IN_RECEIVE_MATERIAL_DETAIL_IN_WAREHOUSE
FOREIGN KEY (WAREHOUSE_ID_DESTINATION) REFERENCES IN_WAREHOUSE (WAREHOUSE_ID)

ALTER TABLE IN_SEND_MATERIAL_HEAD
ADD CONSTRAINT FK_IN_SEND_MATERIAL_HEAD_DB_REASON
FOREIGN KEY (REASON_ID) REFERENCES DB_REASON (REASON_ID)

ALTER TABLE IN_SEND_MATERIAL_DETAIL
ADD CONSTRAINT FK_IN_SEND_MATERIAL_DETAIL_IN_SEND_MATERIAL_HEAD
FOREIGN KEY (SEND_MATERIAL_HEAD_ID) REFERENCES IN_SEND_MATERIAL_HEAD (SEND_MATERIAL_HEAD_ID)

ALTER TABLE IN_SEND_MATERIAL_DETAIL
ADD CONSTRAINT FK_IN_SEND_MATERIAL_DETAIL_IN_WAREHOUSE_SOURCE
FOREIGN KEY (WAREHOUSE_ID_SOURCE) REFERENCES IN_WAREHOUSE (WAREHOUSE_ID)

ALTER TABLE IN_SEND_MATERIAL_DETAIL
ADD CONSTRAINT FK_IN_SEND_MATERIAL_DETAIL_IN_WAREHOUSE_DESTINATION
FOREIGN KEY (WAREHOUSE_ID_DESTINATION) REFERENCES IN_WAREHOUSE (WAREHOUSE_ID)

ALTER TABLE IN_SEND_MATERIAL_DETAIL
ADD CONSTRAINT FK_IN_SEND_MATERIAL_DETAIL_IN_IN_MATERIAL
FOREIGN KEY (MATERIAL_ID) REFERENCES IN_MATERIAL (MATERIAL_ID)