
/****** Object:  Table [dbo].[cbs_system_configuration]    Script Date: 11/19/2014 22:48:45 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[cbs_system_configuration](
	[system_configuration_id] [int] IDENTITY(1,1) NOT NULL,
	[system_configuration_group_code] [nvarchar](20) NULL,
	[system_configuration_code] [nvarchar](20) NULL,
	[system_configuration_name] [nvarchar](100) NULL,
	[description] [nvarchar](500) NULL,
	[value] [nvarchar](1000) NULL,
	[value_type] [nvarchar](50) NULL,
	[active] [bit] NULL,
	[created_by] [nvarchar](30) NOT NULL,
	[created_date] [datetime] NOT NULL,
	[updated_by] [nvarchar](30) NOT NULL,
	[updated_date] [datetime] NOT NULL,
 CONSTRAINT [PK_cbs_system_configuration] PRIMARY KEY CLUSTERED 
(
	[system_configuration_id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[cbs_system_configuration] ON
INSERT [dbo].[cbs_system_configuration] ([system_configuration_id], [system_configuration_group_code], [system_configuration_code], [system_configuration_name], [description], [value], [value_type], [active], [created_by], [created_date], [updated_by], [updated_date]) VALUES (1, N'01', N'0101', N'SessionWarningTime1', N'Warning before Session Expired (minute)', N'10', N'Text', 1, N'System', CAST(0x0000A23F00000000 AS DateTime), N'PPKU', CAST(0x0000A29E012110F8 AS DateTime))
INSERT [dbo].[cbs_system_configuration] ([system_configuration_id], [system_configuration_group_code], [system_configuration_code], [system_configuration_name], [description], [value], [value_type], [active], [created_by], [created_date], [updated_by], [updated_date]) VALUES (2, N'01', N'0102', N'ApplicationStartYear', N'Application Start Year', N'2013', N'Text', 1, N'System', CAST(0x0000A23F00000000 AS DateTime), N'System', CAST(0x0000A23F00000000 AS DateTime))
INSERT [dbo].[cbs_system_configuration] ([system_configuration_id], [system_configuration_group_code], [system_configuration_code], [system_configuration_name], [description], [value], [value_type], [active], [created_by], [created_date], [updated_by], [updated_date]) VALUES (4, N'01', N'0103', N'UploadExcelFileExtension', N'Upload Excel File Extension', N'xlsx', N'Text', 1, N'System', CAST(0x0000A23F00000000 AS DateTime), N'phurin_p', CAST(0x0000A24600B21EB3 AS DateTime))
INSERT [dbo].[cbs_system_configuration] ([system_configuration_id], [system_configuration_group_code], [system_configuration_code], [system_configuration_name], [description], [value], [value_type], [active], [created_by], [created_date], [updated_by], [updated_date]) VALUES (7, N'TMT', N'TMT01-01', N'VacationCashFactorPlanA', N'Vacation Balance Cash factor for employee plan A', N'22', N'Text', 1, N'System', CAST(0x0000A24600000000 AS DateTime), N'phurin_p', CAST(0x0000A24601206126 AS DateTime))
INSERT [dbo].[cbs_system_configuration] ([system_configuration_id], [system_configuration_group_code], [system_configuration_code], [system_configuration_name], [description], [value], [value_type], [active], [created_by], [created_date], [updated_by], [updated_date]) VALUES (9, N'TMT', N'TMT01-02', N'VacationCashFactorPlanB', N'Vacation Balance Cash factor for employee plan B', N'20.5', N'Text', 1, N'System', CAST(0x0000A25000000000 AS DateTime), N'phurin_p', CAST(0x0000A25000000000 AS DateTime))
INSERT [dbo].[cbs_system_configuration] ([system_configuration_id], [system_configuration_group_code], [system_configuration_code], [system_configuration_name], [description], [value], [value_type], [active], [created_by], [created_date], [updated_by], [updated_date]) VALUES (10, N'LOA', N'LOA01', N'OOA Exempt', N'Offshore Overnight Allowance daily rate for Exempt Offshore employee (Baht)', N'1475', N'Text', 1, N'System', CAST(0x0000A25000000000 AS DateTime), N'theera_l', CAST(0x0000A26300E5AE11 AS DateTime))
INSERT [dbo].[cbs_system_configuration] ([system_configuration_id], [system_configuration_group_code], [system_configuration_code], [system_configuration_name], [description], [value], [value_type], [active], [created_by], [created_date], [updated_by], [updated_date]) VALUES (11, N'LOA', N'LOA02', N'OOA Non-Exempt', N'Offshore Overnight Allowance daily rate for Non-exempt Onshore employee (Baht)', N'1215', N'Text', 1, N'System', CAST(0x0000A25000000000 AS DateTime), N'theera_l', CAST(0x0000A26300E5BD54 AS DateTime))
INSERT [dbo].[cbs_system_configuration] ([system_configuration_id], [system_configuration_group_code], [system_configuration_code], [system_configuration_name], [description], [value], [value_type], [active], [created_by], [created_date], [updated_by], [updated_date]) VALUES (14, N'LEV', N'LEV01-01', N'RequestCarryOverStart', N'Setup start date for request carry over', N'01-Dec-2013', N'Date', 1, N'System', CAST(0x0000A25100000000 AS DateTime), N'chonlakan_i', CAST(0x0000A299009E70A9 AS DateTime))
INSERT [dbo].[cbs_system_configuration] ([system_configuration_id], [system_configuration_group_code], [system_configuration_code], [system_configuration_name], [description], [value], [value_type], [active], [created_by], [created_date], [updated_by], [updated_date]) VALUES (15, N'LEV', N'LEV01-02', N'RequestCarryOverEnd', N'Setup end date for request carry over', N'15-Jan-2014', N'Date', 1, N'System', CAST(0x0000A25100000000 AS DateTime), N'PPKU', CAST(0x0000A2A8011B85F4 AS DateTime))
INSERT [dbo].[cbs_system_configuration] ([system_configuration_id], [system_configuration_group_code], [system_configuration_code], [system_configuration_name], [description], [value], [value_type], [active], [created_by], [created_date], [updated_by], [updated_date]) VALUES (18, N'LEV', N'LEV02-01', N'MaxAccumulatedCarryOverOnShore', N'Maximum accumulated carry over for onshore', N'45', N'Text', 1, N'System', CAST(0x0000A25100000000 AS DateTime), N'System', CAST(0x0000A25100000000 AS DateTime))
INSERT [dbo].[cbs_system_configuration] ([system_configuration_id], [system_configuration_group_code], [system_configuration_code], [system_configuration_name], [description], [value], [value_type], [active], [created_by], [created_date], [updated_by], [updated_date]) VALUES (19, N'LEV', N'LEV02-02', N'MaxAccumulatedCarryOverOffShore', N'Maximum accumulated carry over for offshore', N'15', N'Text', 1, N'System', CAST(0x0000A25100000000 AS DateTime), N'System', CAST(0x0000A25100000000 AS DateTime))
INSERT [dbo].[cbs_system_configuration] ([system_configuration_id], [system_configuration_group_code], [system_configuration_code], [system_configuration_name], [description], [value], [value_type], [active], [created_by], [created_date], [updated_by], [updated_date]) VALUES (20, N'LEV', N'LEV03', N'ExtraBonusAccumulatedCarryOver', N'Extra bonus for accumulated carry over', N'3', N'Text', 1, N'System', CAST(0x0000A25100000000 AS DateTime), N'chonlakan_i', CAST(0x0000A26700A7D019 AS DateTime))
INSERT [dbo].[cbs_system_configuration] ([system_configuration_id], [system_configuration_group_code], [system_configuration_code], [system_configuration_name], [description], [value], [value_type], [active], [created_by], [created_date], [updated_by], [updated_date]) VALUES (21, N'LEV', N'LEV04', N'EligibleDaysForOversea', N'Eligible days for oversea employee', N'22', N'Text', 1, N'System', CAST(0x0000A25100000000 AS DateTime), N'System', CAST(0x0000A25100000000 AS DateTime))
INSERT [dbo].[cbs_system_configuration] ([system_configuration_id], [system_configuration_group_code], [system_configuration_code], [system_configuration_name], [description], [value], [value_type], [active], [created_by], [created_date], [updated_by], [updated_date]) VALUES (25, N'HCB', N'HCB01-01', N'RenewMedicalPlanPeriodStrat', N'Setup start date to renew medical plan for employee', N'2013-01-01', N'Date', 1, N'System', CAST(0x0000A25200000000 AS DateTime), N'System', CAST(0x0000A25200000000 AS DateTime))
INSERT [dbo].[cbs_system_configuration] ([system_configuration_id], [system_configuration_group_code], [system_configuration_code], [system_configuration_name], [description], [value], [value_type], [active], [created_by], [created_date], [updated_by], [updated_date]) VALUES (26, N'HCB', N'HCB01-02', N'RenewMedicalPlanPeriodEnd', N'Setup end date to renew medical plan for employee', N'31-Jan-2014', N'Date', 1, N'System', CAST(0x0000A25200000000 AS DateTime), N'KEML', CAST(0x0000A2B0014BB2E2 AS DateTime))
INSERT [dbo].[cbs_system_configuration] ([system_configuration_id], [system_configuration_group_code], [system_configuration_code], [system_configuration_name], [description], [value], [value_type], [active], [created_by], [created_date], [updated_by], [updated_date]) VALUES (29, N'GRA', N'GRA01', N'GratuityReasonForGratuity', N'Gratuity reason code of factor for gratuity calculation', N'G01', N'Text', 1, N'System', CAST(0x0000A25100000000 AS DateTime), N'SPNB', CAST(0x0000A2A000F6EC8C AS DateTime))
INSERT [dbo].[cbs_system_configuration] ([system_configuration_id], [system_configuration_group_code], [system_configuration_code], [system_configuration_name], [description], [value], [value_type], [active], [created_by], [created_date], [updated_by], [updated_date]) VALUES (31, N'LOA', N'LOA03-05', N'PercentOfSalaryRepaymentLimitForHouseLoanVerification', N'Percent of salary repayment limit for house loan verification', N'40', N'Text', 1, N'System', CAST(0x0000A26200000000 AS DateTime), N'theera_l', CAST(0x0000A26301036294 AS DateTime))
INSERT [dbo].[cbs_system_configuration] ([system_configuration_id], [system_configuration_group_code], [system_configuration_code], [system_configuration_name], [description], [value], [value_type], [active], [created_by], [created_date], [updated_by], [updated_date]) VALUES (32, N'LOA', N'LOA03-01', N'LoanRetirementAgeForLoanVerification', N'Retirement age for loan verification', N'55', N'Text', 1, N'System', CAST(0x0000A25000000000 AS DateTime), N'theera_l', CAST(0x0000A26300E5BD54 AS DateTime))
INSERT [dbo].[cbs_system_configuration] ([system_configuration_id], [system_configuration_group_code], [system_configuration_code], [system_configuration_name], [description], [value], [value_type], [active], [created_by], [created_date], [updated_by], [updated_date]) VALUES (33, N'CMP', N'CMP01', N'NumberOfDaysIn1Year', N'Number of days in 1 year for year end bonus factor calculation', N'365', N'Text', 1, N'System', CAST(0x0000A25000000000 AS DateTime), N'theera_l', CAST(0x0000A26300E5BD54 AS DateTime))
INSERT [dbo].[cbs_system_configuration] ([system_configuration_id], [system_configuration_group_code], [system_configuration_code], [system_configuration_name], [description], [value], [value_type], [active], [created_by], [created_date], [updated_by], [updated_date]) VALUES (34, N'LOA', N'LOA03-04', N'MaxRepaymentPeriodForLoanVerification', N'Maximum repayment period for loan verification', N'20', N'Text', 1, N'System', CAST(0x0000A26500000000 AS DateTime), N'System', CAST(0x0000A26500000000 AS DateTime))
INSERT [dbo].[cbs_system_configuration] ([system_configuration_id], [system_configuration_group_code], [system_configuration_code], [system_configuration_name], [description], [value], [value_type], [active], [created_by], [created_date], [updated_by], [updated_date]) VALUES (35, N'LOA', N'LOA03-02', N'MaxHouseLoanAmountForVerification', N'Maximum amount of house loan for loan verification', N'4000000', N'Text', 1, N'System', CAST(0x0000A26500000000 AS DateTime), N'System', CAST(0x0000A26500000000 AS DateTime))
INSERT [dbo].[cbs_system_configuration] ([system_configuration_id], [system_configuration_group_code], [system_configuration_code], [system_configuration_name], [description], [value], [value_type], [active], [created_by], [created_date], [updated_by], [updated_date]) VALUES (37, N'LOA', N'LOA03-03', N'MaxCarLoanAmountForLoanVerification', N'Maximum amount of car loan for loan verification', N'800000', N'Text', 1, N'System', CAST(0x0000A26500000000 AS DateTime), N'System', CAST(0x0000A26500000000 AS DateTime))
INSERT [dbo].[cbs_system_configuration] ([system_configuration_id], [system_configuration_group_code], [system_configuration_code], [system_configuration_name], [description], [value], [value_type], [active], [created_by], [created_date], [updated_by], [updated_date]) VALUES (38, N'LOA', N'LOA04-01', N'RequestForChequeObject', N'Object Account for request for cheque report', N'339014', N'Text', 1, N'System', CAST(0x0000A26500000000 AS DateTime), N'System', CAST(0x0000A26500000000 AS DateTime))
INSERT [dbo].[cbs_system_configuration] ([system_configuration_id], [system_configuration_group_code], [system_configuration_code], [system_configuration_name], [description], [value], [value_type], [active], [created_by], [created_date], [updated_by], [updated_date]) VALUES (39, N'LOA', N'LOA04-02', N'RequestForChequeSub', N'Subsidiary Account for request for cheque report', N'', N'Text', 1, N'System', CAST(0x0000A26500000000 AS DateTime), N'System', CAST(0x0000A26500000000 AS DateTime))
INSERT [dbo].[cbs_system_configuration] ([system_configuration_id], [system_configuration_group_code], [system_configuration_code], [system_configuration_name], [description], [value], [value_type], [active], [created_by], [created_date], [updated_by], [updated_date]) VALUES (40, N'LOA', N'LOA04-03', N'RequestForChequeCostCenterCTEP', N'Cost Center of CTEP for request for cheque report', N'1001000000', N'Text', 1, N'System', CAST(0x0000A26500000000 AS DateTime), N'System', CAST(0x0000A26500000000 AS DateTime))
INSERT [dbo].[cbs_system_configuration] ([system_configuration_id], [system_configuration_group_code], [system_configuration_code], [system_configuration_name], [description], [value], [value_type], [active], [created_by], [created_date], [updated_by], [updated_date]) VALUES (41, N'LOA', N'LOA04-04', N'RequestForChequeCostCenterCASL', N'Cost Center of CASL for request for cheque report', N'1045000000', N'Text', 1, N'System', CAST(0x0000A26500000000 AS DateTime), N'System', CAST(0x0000A26500000000 AS DateTime))
INSERT [dbo].[cbs_system_configuration] ([system_configuration_id], [system_configuration_group_code], [system_configuration_code], [system_configuration_name], [description], [value], [value_type], [active], [created_by], [created_date], [updated_by], [updated_date]) VALUES (42, N'01', N'0104', N'MaximumFileSize', N'Maximum File Size', N'1048576', N'Text', 1, N'System', CAST(0x0000A26900000000 AS DateTime), N'System', CAST(0x0000A26900000000 AS DateTime))
INSERT [dbo].[cbs_system_configuration] ([system_configuration_id], [system_configuration_group_code], [system_configuration_code], [system_configuration_name], [description], [value], [value_type], [active], [created_by], [created_date], [updated_by], [updated_date]) VALUES (45, N'LOA', N'LOA03-06', N'PercentOfSalaryRepaymentLimitForCarLoanVerification', N'Percent of salary repayment limit for car loan verification ', N'30', N'Text', 1, N'System', CAST(0x0000A26F00000000 AS DateTime), N'Chonlakan_i', CAST(0x0000A26F00000000 AS DateTime))
INSERT [dbo].[cbs_system_configuration] ([system_configuration_id], [system_configuration_group_code], [system_configuration_code], [system_configuration_name], [description], [value], [value_type], [active], [created_by], [created_date], [updated_by], [updated_date]) VALUES (48, N'LEV', N'LEV05', N'MaxVacationCarryOver', N'Maximum vacation carry over days for employee request', N'10', N'Text', 1, N'System', CAST(0x0000A2750129EDFB AS DateTime), N'System', CAST(0x0000A2750129EDFB AS DateTime))
INSERT [dbo].[cbs_system_configuration] ([system_configuration_id], [system_configuration_group_code], [system_configuration_code], [system_configuration_name], [description], [value], [value_type], [active], [created_by], [created_date], [updated_by], [updated_date]) VALUES (49, N'LEV', N'LEV06', N'FilePath', N'File path for department annual leave report', N'\\server\shared\', N'Text', 1, N'System', CAST(0x0000A2750129EE19 AS DateTime), N'System', CAST(0x0000A2750129EE19 AS DateTime))
INSERT [dbo].[cbs_system_configuration] ([system_configuration_id], [system_configuration_group_code], [system_configuration_code], [system_configuration_name], [description], [value], [value_type], [active], [created_by], [created_date], [updated_by], [updated_date]) VALUES (50, N'LEV', N'LEV07', N'OverseaAssignment', N'Oversea Assignment Type', N',1,4,6,7,8', N'Text', 1, N'System', CAST(0x0000A27E00C5719A AS DateTime), N'System', CAST(0x0000A27E00C5719A AS DateTime))
INSERT [dbo].[cbs_system_configuration] ([system_configuration_id], [system_configuration_group_code], [system_configuration_code], [system_configuration_name], [description], [value], [value_type], [active], [created_by], [created_date], [updated_by], [updated_date]) VALUES (51, N'02', N'0201', N'MailServer', N'', N'softmail.softsquaregroup.com', N'Text', 1, N'System', CAST(0x0000A28500CDE282 AS DateTime), N'System', CAST(0x0000A28500CDE282 AS DateTime))
INSERT [dbo].[cbs_system_configuration] ([system_configuration_id], [system_configuration_group_code], [system_configuration_code], [system_configuration_name], [description], [value], [value_type], [active], [created_by], [created_date], [updated_by], [updated_date]) VALUES (52, N'02', N'0202', N'MailServerPort', N'', N'25', N'Text', 1, N'System', CAST(0x0000A28500CDE282 AS DateTime), N'System', CAST(0x0000A28500CDE282 AS DateTime))
INSERT [dbo].[cbs_system_configuration] ([system_configuration_id], [system_configuration_group_code], [system_configuration_code], [system_configuration_name], [description], [value], [value_type], [active], [created_by], [created_date], [updated_by], [updated_date]) VALUES (53, N'02', N'0203', N'SystemEmailAddress', N'', N'phurin_p@softsquaregroup.com', N'Text', 1, N'System', CAST(0x0000A28500CDE282 AS DateTime), N'System', CAST(0x0000A28500CDE282 AS DateTime))
INSERT [dbo].[cbs_system_configuration] ([system_configuration_id], [system_configuration_group_code], [system_configuration_code], [system_configuration_name], [description], [value], [value_type], [active], [created_by], [created_date], [updated_by], [updated_date]) VALUES (54, N'02', N'0204', N'SystemEmailName', N'', N'softsquaregroup', N'Text', 1, N'System', CAST(0x0000A28500CDE282 AS DateTime), N'System', CAST(0x0000A28500CDE282 AS DateTime))
INSERT [dbo].[cbs_system_configuration] ([system_configuration_id], [system_configuration_group_code], [system_configuration_code], [system_configuration_name], [description], [value], [value_type], [active], [created_by], [created_date], [updated_by], [updated_date]) VALUES (55, N'03', N'030101', N'ApproveVacationCarryOverEmailSubject', N'Email Subject for ApproveVacationCarryOver', N'Result Approve Vacation Carry Over in Compensation and Benefit system', N'Text', 1, N'System', CAST(0x0000A28500EED19A AS DateTime), N'System', CAST(0x0000A28500EED19A AS DateTime))
INSERT [dbo].[cbs_system_configuration] ([system_configuration_id], [system_configuration_group_code], [system_configuration_code], [system_configuration_name], [description], [value], [value_type], [active], [created_by], [created_date], [updated_by], [updated_date]) VALUES (56, N'03', N'030102', N'ApproveVacationCarryOverEmailBody', N'Email Body for ApproveVacationCarryOver', N'<body style="font-name:Arial; font-size:10pt;">  This is an automated e-mail message generated by the Compensation and Benefit system. Please do not reply 

to this e-mail.<br/>  ------------------------------------------------------------------------------------------------------------------------<br/><br/>  

Dear [ToName],<br/><br/>  

This e-mail is to notify you that  <br/><br/>

[Detail]

<br/>  For more detail, please click <a 

href="[URL]">Compensation and Benefit system</a>.  <br/><br/><br/>  Thank You,<br/> Compensation and Benefit system.  </body> ', N'Text', 1, N'System', CAST(0x0000A28500EED19A AS DateTime), N'System', CAST(0x0000A28500EED19A AS DateTime))
INSERT [dbo].[cbs_system_configuration] ([system_configuration_id], [system_configuration_group_code], [system_configuration_code], [system_configuration_name], [description], [value], [value_type], [active], [created_by], [created_date], [updated_by], [updated_date]) VALUES (57, N'03', N'030201', N'RejectVacationCarryOverEmailSubject', N'Email Subject for RejectVacationCarryOver', N'Your vacation carry over request has been rejected.', N'Text', 1, N'System', CAST(0x0000A28500CDE282 AS DateTime), N'System', CAST(0x0000A28500CDE282 AS DateTime))
INSERT [dbo].[cbs_system_configuration] ([system_configuration_id], [system_configuration_group_code], [system_configuration_code], [system_configuration_name], [description], [value], [value_type], [active], [created_by], [created_date], [updated_by], [updated_date]) VALUES (58, N'03', N'030202', N'RejectVacationCarryOverEmailBody', N'Email Body for RejectVacationCarryOver', N'<body style="font-name:Arial; font-size:10pt;">  This is an automated e-mail message generated by the Compensation and Benefit system. Please do not reply to this e-mail.<br/>  ------------------------------------------------------------------------------------------------------------------------<br/><br/>      Dear [ToName],<br/><br/>   This e-mail notify you that your vacation carry over request has been rejected as below detail.<br/><br/>    [Detail]    <br/>  For more detail, please click <a     href="[URL]">Compensation and Benefit system</a>.  <br/><br/><br/>  Thank You,<br/> Compensation and Benefit system.  </body>', N'Text', 1, N'System', CAST(0x0000A28500CDE282 AS DateTime), N'System', CAST(0x0000A28500CDE282 AS DateTime))
INSERT [dbo].[cbs_system_configuration] ([system_configuration_id], [system_configuration_group_code], [system_configuration_code], [system_configuration_name], [description], [value], [value_type], [active], [created_by], [created_date], [updated_by], [updated_date]) VALUES (59, N'03', N'030301', N'RequestVacationCarryOverEmailSubject', N'Email Subject for RequestVacationCarryOver', N'Result Request Vacation Carry Over in Compensation and Benefit system', N'Text', 1, N'System', CAST(0x0000A29800AE9BB2 AS DateTime), N'System', CAST(0x0000A29800AE9BB2 AS DateTime))
INSERT [dbo].[cbs_system_configuration] ([system_configuration_id], [system_configuration_group_code], [system_configuration_code], [system_configuration_name], [description], [value], [value_type], [active], [created_by], [created_date], [updated_by], [updated_date]) VALUES (60, N'03', N'030302', N'RequestVacationCarryOverEmailBody', N'Email Body for RequestVacationCarryOver', N'<body style="font-name:Arial; font-size:10pt;">  This is an automated e-mail message generated by the Compensation and Benefit system. Please do not reply     to this e-mail.<br/>  ------------------------------------------------------------------------------------------------------------------------<br/><br/>      Dear [ToName],<br/><br/>      This e-mail is to notify you that  <br/><br/>    [Detail]    <br/>  For more detail, please click <a     href="[URL]">Compensation and Benefit system</a>.  <br/><br/><br/>  Thank You,<br/> Compensation and Benefit system.  </body> ', N'Text', 1, N'System', CAST(0x0000A29800AE9BB2 AS DateTime), N'System', CAST(0x0000A29800AE9BB2 AS DateTime))
INSERT [dbo].[cbs_system_configuration] ([system_configuration_id], [system_configuration_group_code], [system_configuration_code], [system_configuration_name], [description], [value], [value_type], [active], [created_by], [created_date], [updated_by], [updated_date]) VALUES (61, N'01', N'0105', N'Link URL', N'For Send Email', N'http://localhost:3845', N'Text', 1, N'System', CAST(0x0000A29800B8A1E2 AS DateTime), N'System', CAST(0x0000A29800B8A1E2 AS DateTime))
INSERT [dbo].[cbs_system_configuration] ([system_configuration_id], [system_configuration_group_code], [system_configuration_code], [system_configuration_name], [description], [value], [value_type], [active], [created_by], [created_date], [updated_by], [updated_date]) VALUES (62, N'UAR', N'UAR01', N'Email Steward', N'Email Address of Steward', N'phurin_p@softsquaregroup.com', N'Text', 1, N'System', CAST(0x0000A2A000FA8B41 AS DateTime), N'System', CAST(0x0000A2A000FA8B41 AS DateTime))
INSERT [dbo].[cbs_system_configuration] ([system_configuration_id], [system_configuration_group_code], [system_configuration_code], [system_configuration_name], [description], [value], [value_type], [active], [created_by], [created_date], [updated_by], [updated_date]) VALUES (63, N'03', N'030401', N'Generate UAR EmailSubject', N'Email Subject for Generate UAR', N'Result Generate UAR in Compensation and Benefit system', N'Text', 1, N'System', CAST(0x0000A2A000FC10B6 AS DateTime), N'System', CAST(0x0000A2A000FC10B6 AS DateTime))
INSERT [dbo].[cbs_system_configuration] ([system_configuration_id], [system_configuration_group_code], [system_configuration_code], [system_configuration_name], [description], [value], [value_type], [active], [created_by], [created_date], [updated_by], [updated_date]) VALUES (64, N'03', N'030402', N'Generate UAR EmailBody', N'Email Body for Generate UAR', N'<body style="font-name:Arial; font-size:10pt;">  This is an automated e-mail message generated by the Compensation and Benefit system. Please do not reply     to this e-mail.<br/>  ------------------------------------------------------------------------------------------------------------------------<br/><br/>      Dear [ToName],<br/><br/>      This e-mail is to notify you that  <br/><br/>    [Detail]    <br/>  For more detail, please click <a     href="[URL]">Compensation and Benefit system</a>.  <br/><br/><br/>  Thank You,<br/> Compensation and Benefit system.  </body> ', N'Text', 1, N'System', CAST(0x0000A2A000FC10B6 AS DateTime), N'System', CAST(0x0000A2A000FC10B6 AS DateTime))
INSERT [dbo].[cbs_system_configuration] ([system_configuration_id], [system_configuration_group_code], [system_configuration_code], [system_configuration_name], [description], [value], [value_type], [active], [created_by], [created_date], [updated_by], [updated_date]) VALUES (66, N'HCB', N'HCB02-01', N'Insuranc Type for Force by Policy', N'Insuranc Type for Member Force by Policy', N'H', N'Text', 1, N'System', CAST(0x0000A2A000000000 AS DateTime), N'System', CAST(0x0000A2A000000000 AS DateTime))
INSERT [dbo].[cbs_system_configuration] ([system_configuration_id], [system_configuration_group_code], [system_configuration_code], [system_configuration_name], [description], [value], [value_type], [active], [created_by], [created_date], [updated_by], [updated_date]) VALUES (67, N'HCB', N'HCB01-03', N'Year for Request Renew Medicla Plan', N'Current year for  renew medical plan request', N'2013', N'Text', 1, N'System', CAST(0x0000A2A700000000 AS DateTime), N'System', CAST(0x0000A2A700000000 AS DateTime))
SET IDENTITY_INSERT [dbo].[cbs_system_configuration] OFF
/****** Object:  ForeignKey [FK_cbs_system_configuration_cbs_system_configuration_group]    Script Date: 11/19/2014 22:48:45 ******/