USE POS
--DELETE FROM [so_menu]
--DBCC CHECKIDENT ('[so_menu]', RESEED, 0) 

INSERT INTO [so_menu] ([menu_code] ,[menu_name] ,menu_reference_id,[active] ,[created_by] ,[created_date] ,[updated_by],[updated_date])
VALUES   ('001','ยำ',null,1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('002',' ยำปลาดุกฟูลุยสวน',(select TOP 1 menu_id FROM so_menu WHERE menu_code='001'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('003',' ยำปลาดุกฟู',(select TOP 1 menu_id FROM so_menu WHERE menu_code='001'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('004',' ยำไข่เยี่ยวม้า',(select TOP 1 menu_id FROM so_menu WHERE menu_code='001'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('005',' ยำหมูกรอบ',(select TOP 1 menu_id FROM so_menu WHERE menu_code='001'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('006',' ยำหมูยอ / ทะเล,รวม',(select TOP 1 menu_id FROM so_menu WHERE menu_code='001'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('007',' ยำกุนเชียง',(select TOP 1 menu_id FROM so_menu WHERE menu_code='001'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('008',' ยำแหนม',(select TOP 1 menu_id FROM so_menu WHERE menu_code='001'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('009',' ยำวุ้นเส้นหมู,ไก่ / ทะเล,รวม',(select TOP 1 menu_id FROM so_menu WHERE menu_code='001'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('010',' ยำมาม่าหมู,ไก่ / ทะเล,รวม',(select TOP 1 menu_id FROM so_menu WHERE menu_code='001'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('011',' ยำก้านคะน้ากุ้งสด',(select TOP 1 menu_id FROM so_menu WHERE menu_code='001'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('012',' ยำกบทอด',(select TOP 1 menu_id FROM so_menu WHERE menu_code='001'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('013',' ยำปลาหมึก',(select TOP 1 menu_id FROM so_menu WHERE menu_code='001'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('014',' ยำรวมมิตรทะเล+เห็ด',(select TOP 1 menu_id FROM so_menu WHERE menu_code='001'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('015',' ยำตะไคร้ทะเล',(select TOP 1 menu_id FROM so_menu WHERE menu_code='001'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('016',' ยำปลากระป๋อง',(select TOP 1 menu_id FROM so_menu WHERE menu_code='001'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('017',' ยำพล่ากุ้ง',(select TOP 1 menu_id FROM so_menu WHERE menu_code='001'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('018',' ยำหมูมะนาว',(select TOP 1 menu_id FROM so_menu WHERE menu_code='001'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('019',' ยำเห็ดรวม/รวมทะเล',(select TOP 1 menu_id FROM so_menu WHERE menu_code='001'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('020',' ยำหมูกรอบน้ำพริกเผา',(select TOP 1 menu_id FROM so_menu WHERE menu_code='001'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('021',' ยำหมูกรอบมะม่วง',(select TOP 1 menu_id FROM so_menu WHERE menu_code='001'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('022','อาหารจานเดียว',null,1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('023',' ผัดกระเพราหมู,ไก่ / หมูกรอบ,รวมมิตร,ทะเล ',(select TOP 1 menu_id FROM so_menu WHERE menu_code='022'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('024',' ผัดกระเพราหมูแดดเดียว,ปลาดุกพริกแกงราดข้าว',(select TOP 1 menu_id FROM so_menu WHERE menu_code='022'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('025',' ผัดไข่เยี่ยวม้ากระเพรากรอบราดข้าว',(select TOP 1 menu_id FROM so_menu WHERE menu_code='022'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('026',' ผัดพริกแกงหมู,ไก่ / หมูกรอบ,รวมมิตร,ทะเล ',(select TOP 1 menu_id FROM so_menu WHERE menu_code='022'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('027',' ผัดพริกเผาหมู,ไก่ / หมูกรอบ,รวมมิตร,ทะเล',(select TOP 1 menu_id FROM so_menu WHERE menu_code='022'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('028',' ผัดพริกหยวกหมู,ไก่ / หมูกรอบ,รวมมิตร,ทะเล ',(select TOP 1 menu_id FROM so_menu WHERE menu_code='022'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('029',' ผัดขี้เมาหมู,ไก่ / หมูกรอบ,กุ้ง,หมึก,รวมมิตร,ทะเล',(select TOP 1 menu_id FROM so_menu WHERE menu_code='022'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('030',' ผัดเผ็ดหมู,ไก่ / กุ้ง,หมึก,กบ,นก,รวมมิตร,ทะเล',(select TOP 1 menu_id FROM so_menu WHERE menu_code='022'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('031',' ผัดคะน้าหมูกรอบ, ผัดคะน้าปลาเค็มราดข้าว',(select TOP 1 menu_id FROM so_menu WHERE menu_code='022'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('032',' ผัดฉ่าปลาดุก / ผัดฉ่ารวมมิตร,ทะเล',(select TOP 1 menu_id FROM so_menu WHERE menu_code='022'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('033',' ผัดพริกไทดำหมู,ไก่ / หมูกรอบ,รวมมิตร,ทะเล ',(select TOP 1 menu_id FROM so_menu WHERE menu_code='022'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('034',' ตับหมู (ผัดฉ่า,ผัดพริกแกง,ผัดพริกสด,กระเทียม) ',(select TOP 1 menu_id FROM so_menu WHERE menu_code='022'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('035',' ผัดผงกระหรี่หมู,ไก่ / ทะเล,รวมมิตร',(select TOP 1 menu_id FROM so_menu WHERE menu_code='022'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('036',' ปลากระพง (ผัดฉ่า,ผัดพริกแกง,ผัดพริกสด,กระเทียม) ',(select TOP 1 menu_id FROM so_menu WHERE menu_code='022'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('037',' ปลาช่อน (ผัดฉ่า,ผัดพริกแกง,ผัดพริกสด,กระเทียม) ',(select TOP 1 menu_id FROM so_menu WHERE menu_code='022'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('038',' ผัดกระเทียมพริกไทยหมู, ไก่ / หมูกรอบ,ทะเล ',(select TOP 1 menu_id FROM so_menu WHERE menu_code='022'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('039',' หมูทอด, กุนเชียงทอด,หมูยอทอด ราดข้าว',(select TOP 1 menu_id FROM so_menu WHERE menu_code='022'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('040',' ข้าวต้มหมู,ไก่ / ทะเล,กระดูกหมู, ปลา, รวมมิตร',(select TOP 1 menu_id FROM so_menu WHERE menu_code='022'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('041',' ข้าวผัดปู, ข้าวผัดแหนม, ',(select TOP 1 menu_id FROM so_menu WHERE menu_code='022'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('042',' ข้าวผัดโป๊ะแตก / ข้าวผัดปลาเค็ม',(select TOP 1 menu_id FROM so_menu WHERE menu_code='022'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('043',' ข้าวผัดผงกระหรี่หมู,ไก่ /  รวมมิตร, ทะเล, ปู',(select TOP 1 menu_id FROM so_menu WHERE menu_code='022'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('044',' ข้าวผัดหมู,ไก่ / กุ้ง,ปลาหมึก,ทะเล,รวมมิตร',(select TOP 1 menu_id FROM so_menu WHERE menu_code='022'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('045',' ข้าวไข่เจียว / ไข่เจียวหมูสับ / แหนม,กุ้งสับ',(select TOP 1 menu_id FROM so_menu WHERE menu_code='022'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('046',' ข้าวผัดไส้กรอก,กุนเชียง , กระเพราหมูยอ,ไส้กรอก',(select TOP 1 menu_id FROM so_menu WHERE menu_code='022'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('047',' ข้าวผัดขี้เมาหมู,ไก่ / หมูกรอบ,กุ้ง,หมึก,ทะเล',(select TOP 1 menu_id FROM so_menu WHERE menu_code='022'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('048',' ข้าวผัดน้ำพริกเผา หมู,ไก่ / กุ้ง,หมึก,ทะเล',(select TOP 1 menu_id FROM so_menu WHERE menu_code='022'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('049',' ข้าวผัดต้มยำ หมู,ไก่ / กุ้ง,หมึก,รวมมิตร,ทะเล',(select TOP 1 menu_id FROM so_menu WHERE menu_code='022'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('050',' ข้าวผัดแกงเขียนหวาน หมู,ไก่ / กุ้ง,หมึก, ทะเล',(select TOP 1 menu_id FROM so_menu WHERE menu_code='022'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('051',' ก๋วยเตี๋ยวต้มยำ หมู,ไก่ / กุ้ง,ปลาหมึก ',(select TOP 1 menu_id FROM so_menu WHERE menu_code='022'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('052',' ก๋วยเตี๋ยวต้มแซ่บ หมู,ไก่ / กุ้ง,ปลาหมึก ',(select TOP 1 menu_id FROM so_menu WHERE menu_code='022'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('053',' สุกี้น้ำ - แห้ง หมู,ไก่ / กุ้ง,ปลาหมึก / รวมมิตร',(select TOP 1 menu_id FROM so_menu WHERE menu_code='022'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('054',' ผัดซีอิ๊ว หมู,ไก่ / กุ้ง,ปลาหมึก ',(select TOP 1 menu_id FROM so_menu WHERE menu_code='022'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('055',' ราดหน้า หมู,ไก่ / กุ้ง,ปลาหมึก ',(select TOP 1 menu_id FROM so_menu WHERE menu_code='022'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('056',' มาม่าผัดขี้เมาหมู,ไก่ / ทะเล,รวมมิตร',(select TOP 1 menu_id FROM so_menu WHERE menu_code='022'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('057',' มาม่าต้มยำหมู,ไก่ /  ทะเล,รวมมิตร',(select TOP 1 menu_id FROM so_menu WHERE menu_code='022'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('058',' มะกะโรนีผัดขี้เมา/ผัดฉ่าหมู, ไก่ / ทะเล,รวม',(select TOP 1 menu_id FROM so_menu WHERE menu_code='022'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('059',' มะกะโรนีผัดซอสหมู, ไก่ / ทะเล,รวมมิตร',(select TOP 1 menu_id FROM so_menu WHERE menu_code='022'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('060',' มะกะโรนีต้มยำหมู, ไก่ / ทะเล,รวมมิตร',(select TOP 1 menu_id FROM so_menu WHERE menu_code='022'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('061',' สปาเก็ตตี้ผัดขี้เมา/ผัดฉ่าหมู, ไก่ / ทะเล,รวม',(select TOP 1 menu_id FROM so_menu WHERE menu_code='022'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('062',' สปาเก็ตตี้ผัดซอสหมู, ไก่ / ทะเล,รวมมิตร',(select TOP 1 menu_id FROM so_menu WHERE menu_code='022'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('063',' สปาเก็ตตี้ต้มยำหมู, ไก่ / ทะเล,รวมมิตร',(select TOP 1 menu_id FROM so_menu WHERE menu_code='022'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('064',' สปาเก๊ตตี้เขียวหวานหมู, ไก่ / ทะเล,รวม',(select TOP 1 menu_id FROM so_menu WHERE menu_code='022'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('065',' สปาเก็ตตี้ผัดพริกเผาทะเล',(select TOP 1 menu_id FROM so_menu WHERE menu_code='022'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('066',' ผัดผักกระเชต / เนื้อสัตว์',(select TOP 1 menu_id FROM so_menu WHERE menu_code='022'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('067',' ผัดผักบุ้ง / เนื้อสัตว์',(select TOP 1 menu_id FROM so_menu WHERE menu_code='022'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('068',' ผัดดอกคะน้าหมู,ไก่ / หมูกรอบ',(select TOP 1 menu_id FROM so_menu WHERE menu_code='022'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('069',' ผัดเห็ดน้ำมันหอยหมู,ไก่ / หมูกรอบ',(select TOP 1 menu_id FROM so_menu WHERE menu_code='022'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('070',' ผัดไทแห้ง / กุ้งสด / ทะเล ',(select TOP 1 menu_id FROM so_menu WHERE menu_code='022'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('071',' ผัดเส้นหมี่+ผักกระเชด+ทะเล',(select TOP 1 menu_id FROM so_menu WHERE menu_code='022'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('072',' ราดหน้าผักรวม หมู ไก่ / ทะเล รวมมิตร',(select TOP 1 menu_id FROM so_menu WHERE menu_code='022'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('073',' ราดหน้าหมี่กรอบ หมูไก่ / ทะเล รวมมิตร',(select TOP 1 menu_id FROM so_menu WHERE menu_code='022'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('074',' กระเพราไก่สับ',(select TOP 1 menu_id FROM so_menu WHERE menu_code='022'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('075',' ผัดขี้เมาวุ้นเส้นรวมมิตร',(select TOP 1 menu_id FROM so_menu WHERE menu_code='022'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('076','ต้ม',null,1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('077',' ต้มจืดเต้าหู้วุ้นเส้นหมูสับ',(select TOP 1 menu_id FROM so_menu WHERE menu_code='076'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('078',' ต้มจืดเต้าหู้กระดูกหมูอ่อน',(select TOP 1 menu_id FROM so_menu WHERE menu_code='076'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('079',' ต้มจืดไข่เจียว',(select TOP 1 menu_id FROM so_menu WHERE menu_code='076'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('080',' ต้มจืดเต้าหู้+หมู+สาหร่าย',(select TOP 1 menu_id FROM so_menu WHERE menu_code='076'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('081',' ต้มจืดรวมมิตร',(select TOP 1 menu_id FROM so_menu WHERE menu_code='076'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('082',' ต้มจืดปลาหมึกยัดใส้',(select TOP 1 menu_id FROM so_menu WHERE menu_code='076'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('083',' ต้มจืดผักกาดกระป๋อง',(select TOP 1 menu_id FROM so_menu WHERE menu_code='076'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('084',' ต้มจืดเต้าหู้หมูสับ',(select TOP 1 menu_id FROM so_menu WHERE menu_code='076'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('085',' ต้มซุปเปอร์ตีนไก่',(select TOP 1 menu_id FROM so_menu WHERE menu_code='076'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('086',' ต้มแซ่บกระดูกหมู',(select TOP 1 menu_id FROM so_menu WHERE menu_code='076'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('087',' ต้มแซบรวม',(select TOP 1 menu_id FROM so_menu WHERE menu_code='076'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('088',' ต้มยำหมู,ไก่',(select TOP 1 menu_id FROM so_menu WHERE menu_code='076'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('089',' ต้มยำกุ้ง, ปลาหมึก ',(select TOP 1 menu_id FROM so_menu WHERE menu_code='076'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('090',' ต้มยำทะเล, รวมมิตร',(select TOP 1 menu_id FROM so_menu WHERE menu_code='076'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('091',' ต้มโคล้งปลาย่าง',(select TOP 1 menu_id FROM so_menu WHERE menu_code='076'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('092',' ต้มยำโป๊ะแตก',(select TOP 1 menu_id FROM so_menu WHERE menu_code='076'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('093',' ต้มยำปลากระพง',(select TOP 1 menu_id FROM so_menu WHERE menu_code='076'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('094',' ต้มยำปลาช่อน',(select TOP 1 menu_id FROM so_menu WHERE menu_code='076'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('095',' ต้มยำพุงปลา+หัวปลาช่อน',(select TOP 1 menu_id FROM so_menu WHERE menu_code='076'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('096',' ต้มข่าไก่',(select TOP 1 menu_id FROM so_menu WHERE menu_code='076'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('097','ทอด',null,1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('098',' ปีกไก่ทอดน้ำปลา',(select TOP 1 menu_id FROM so_menu WHERE menu_code='097'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('099',' หมูยอทอด',(select TOP 1 menu_id FROM so_menu WHERE menu_code='097'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('100',' หมูแดดเดียว',(select TOP 1 menu_id FROM so_menu WHERE menu_code='097'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('101',' กุ้ง, ปลาหมึกชุบแป้งทอด',(select TOP 1 menu_id FROM so_menu WHERE menu_code='097'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('102',' กระดูกหมูอ่อนทอด',(select TOP 1 menu_id FROM so_menu WHERE menu_code='097'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('103',' กบ, นกทอดกระเทียม',(select TOP 1 menu_id FROM so_menu WHERE menu_code='097'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('104',' แหนมชุปไข่ทอด',(select TOP 1 menu_id FROM so_menu WHERE menu_code='097'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('105',' ใส้กรอกหมู',(select TOP 1 menu_id FROM so_menu WHERE menu_code='097'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('106',' เทมปุระกุ้งผักรวม',(select TOP 1 menu_id FROM so_menu WHERE menu_code='097'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('107',' หมูกรอบทอด + น้ำจิ้ม',(select TOP 1 menu_id FROM so_menu WHERE menu_code='097'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('108',' แหนมกระดูกหมูอ่อนทอด',(select TOP 1 menu_id FROM so_menu WHERE menu_code='097'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('109',' กุนเชียงทอด',(select TOP 1 menu_id FROM so_menu WHERE menu_code='097'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('110',' ปลา/กุ้ง',null,1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('111',' ปลากระพงทอดน้ำปลา (เป็นตัว) ',(select TOP 1 menu_id FROM so_menu WHERE menu_code='110'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('112',' ปลากระพงสามรส (เป็นตัว)',(select TOP 1 menu_id FROM so_menu WHERE menu_code='110'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('113',' ปลากระพงสมุนไพร (เป็นตัว)',(select TOP 1 menu_id FROM so_menu WHERE menu_code='110'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('114',' ปลากระพงนึ่งมะนาว (เป็นตัว)',(select TOP 1 menu_id FROM so_menu WHERE menu_code='110'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('115',' ปลากระพงต้มยำ (เป็นตัว)',(select TOP 1 menu_id FROM so_menu WHERE menu_code='110'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('116',' ปลาทับทิมทอดน้ำปลา (เป็นตัว)',(select TOP 1 menu_id FROM so_menu WHERE menu_code='110'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('117',' ปลาทับทิมสามรส (เป็นตัว)',(select TOP 1 menu_id FROM so_menu WHERE menu_code='110'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('118',' ปลาทับทิมสมุนไพร (เป็นตัว)',(select TOP 1 menu_id FROM so_menu WHERE menu_code='110'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('119',' ปลาทับทิมทอดกระเทียม (เป็นตัว)',(select TOP 1 menu_id FROM so_menu WHERE menu_code='110'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('120',' ปลาช่อนลุยสวน (เป็นตัว)',(select TOP 1 menu_id FROM so_menu WHERE menu_code='110'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('121',' แกงส้มปลาช่อนแป๊ะซะ (เป็นตัว)',(select TOP 1 menu_id FROM so_menu WHERE menu_code='110'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('122',' ยำปลาสมุนไพร (เป็นชิ้น) ปลากระพง / ปลาช่อน',(select TOP 1 menu_id FROM so_menu WHERE menu_code='110'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('123',' ปลาหมึกนึ่งมะนาว',(select TOP 1 menu_id FROM so_menu WHERE menu_code='110'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('124',' ปลาผัดคื่นช่าย (เป็นชิ้น) ปลากระพง / ปลาช่อน',(select TOP 1 menu_id FROM so_menu WHERE menu_code='110'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('125',' กุ้งอบวุ้นเส้น / กุ้งแช่น้ำปลา',(select TOP 1 menu_id FROM so_menu WHERE menu_code='110'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('126',' ผัดเนื้อปลาทอดสมุนไพร (ปลากระพง/ ปลาช่อน/ปลาดุก)',(select TOP 1 menu_id FROM so_menu WHERE menu_code='110'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('127','ผัด',null,1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('128',' ผัดกระเพรา หมู, ไก่',(select TOP 1 menu_id FROM so_menu WHERE menu_code='127'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('129',' ผัดกระเพราหมูกรอบ / กุ้ง / ปลาหมึก / รวมมิตร',(select TOP 1 menu_id FROM so_menu WHERE menu_code='127'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('130',' ผัดกระเพรากรอบ+ไข่เยี่ยวม้า',(select TOP 1 menu_id FROM so_menu WHERE menu_code='127'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('131',' ผัดพริกแกงหมูกรอบ / หมู / ไก่ / ทะเล / รวมมิตร',(select TOP 1 menu_id FROM so_menu WHERE menu_code='127'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('132',' ผัดพริกแกงปลาดุกฟู',(select TOP 1 menu_id FROM so_menu WHERE menu_code='127'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('133',' ผัดขี้เมาทะเล',(select TOP 1 menu_id FROM so_menu WHERE menu_code='127'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('134',' ผัดพริกหยวก หมู, ไก่',(select TOP 1 menu_id FROM so_menu WHERE menu_code='127'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('135',' ผัดพริกหยวก หมูกรอบ, กุ้ง, ปลาหมึก,รวมมิตร',(select TOP 1 menu_id FROM so_menu WHERE menu_code='127'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('136',' ผัดผักกะเฉดหมูกรอบ, ผักบุ้งหมูกรอบ',(select TOP 1 menu_id FROM so_menu WHERE menu_code='127'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('137',' ผัดวุ้นเส้นหมูสับ / กุ้ง',(select TOP 1 menu_id FROM so_menu WHERE menu_code='127'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('138',' ผัดกระเพราหมูแดดเดียว',(select TOP 1 menu_id FROM so_menu WHERE menu_code='127'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('139',' ผัดเผ็ด หมู, ไก่',(select TOP 1 menu_id FROM so_menu WHERE menu_code='127'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('140',' ผัดเผ็ด ทะเล / รวมมิตร / กบ, นก',(select TOP 1 menu_id FROM so_menu WHERE menu_code='127'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('141',' ผัดพริกแกงปลาดุกทอดกรอบ',(select TOP 1 menu_id FROM so_menu WHERE menu_code='127'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('142',' ผัดเต้าหู้น้ำแดง',(select TOP 1 menu_id FROM so_menu WHERE menu_code='127'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('143',' ผัดผงกระหรี่หมู,ไก่ / ทะเล,รวมมิตร',(select TOP 1 menu_id FROM so_menu WHERE menu_code='127'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('144',' ผัดผักรวมน้ำมันหอย/เนื้อสัตว์/ทะเล,รวม',(select TOP 1 menu_id FROM so_menu WHERE menu_code='127'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('145',' ผัดคะน้าน้ำมันหอย/เนื้อสัตว์/ทะเล,รวม',(select TOP 1 menu_id FROM so_menu WHERE menu_code='127'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('146',' ผัดคะน้าปลาเค็ม, ผัดคะน้าหมูกรอบ',(select TOP 1 menu_id FROM so_menu WHERE menu_code='127'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('147',' ผัดผักบุ้งหมูกรอบ',(select TOP 1 menu_id FROM so_menu WHERE menu_code='127'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('148',' ผัดพริกเผาหมูกรอบ, รวมมิตร',(select TOP 1 menu_id FROM so_menu WHERE menu_code='127'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('149',' ผัดเปรี้ยวหวานหมู,ไก่/ทะเล,รวมมิตร',(select TOP 1 menu_id FROM so_menu WHERE menu_code='127'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('150',' ไก่ผัดเม็ดมะม่วง',(select TOP 1 menu_id FROM so_menu WHERE menu_code='127'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('151',' ผัดพริกไทดำ หมู, ไก่',(select TOP 1 menu_id FROM so_menu WHERE menu_code='127'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('152',' ผัดพริกไทดำ กุ้ง,หมึก,รวมมิตร,ทะเล',(select TOP 1 menu_id FROM so_menu WHERE menu_code='127'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('153',' ผัดพริกไทดำ / ปลาดุก /ปลาช่อน ',(select TOP 1 menu_id FROM so_menu WHERE menu_code='127'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('154',' ผัดกระเทียมหมู, ไก่ / ทะเล , รวมมิตร',(select TOP 1 menu_id FROM so_menu WHERE menu_code='127'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('155',' ผัดฉ่าหมูกรอบ / รวมมิตร / ปลาดุก ',(select TOP 1 menu_id FROM so_menu WHERE menu_code='127'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('156',' แกงเขียวหวาน หมู /  ไก่ / ปลาดุก',(select TOP 1 menu_id FROM so_menu WHERE menu_code='127'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('157',' แกงคั่ว หมู / ไก่ / ปลาดุก',(select TOP 1 menu_id FROM so_menu WHERE menu_code='127'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('158','ไข่',null,1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('159',' ไข่เจียว',(select TOP 1 menu_id FROM so_menu WHERE menu_code='158'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('160',' ไข่เจียวหมูสับ,ไข่เจียวแหนม',(select TOP 1 menu_id FROM so_menu WHERE menu_code='158'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('161',' ไข่เจียวกุ้ง',(select TOP 1 menu_id FROM so_menu WHERE menu_code='158'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('162',' ไข่ยัดใส้',(select TOP 1 menu_id FROM so_menu WHERE menu_code='158'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('163','ส้มตำ, ลาบ, น้ำตก',null,1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('164',' ส้มตำปู, ส้มตำปลาร้า, ส้มตำปูปลาร้า, ส้มตำไทย',(select TOP 1 menu_id FROM so_menu WHERE menu_code='163'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('165',' ส้มตำไทยปู',(select TOP 1 menu_id FROM so_menu WHERE menu_code='163'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('166',' ส้มตำไข่เค็ม',(select TOP 1 menu_id FROM so_menu WHERE menu_code='163'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('167',' ส้มตำปลาดุกฟู ',(select TOP 1 menu_id FROM so_menu WHERE menu_code='163'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('168',' ตำมะม่วง, ยำมะม่วงกุ้งแห้ง',(select TOP 1 menu_id FROM so_menu WHERE menu_code='163'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('169',' ลาบหมู, ลาบไก่, ลาบปลาดุก',(select TOP 1 menu_id FROM so_menu WHERE menu_code='163'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('170',' ลาบปลาหมึก',(select TOP 1 menu_id FROM so_menu WHERE menu_code='163'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('171',' ตับหวาน',(select TOP 1 menu_id FROM so_menu WHERE menu_code='163'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('172',' น้ำตกหมูกรอบ',(select TOP 1 menu_id FROM so_menu WHERE menu_code='163'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('173',' เส้นหมี่ผัด, เส้นเล็กผัด',(select TOP 1 menu_id FROM so_menu WHERE menu_code='163'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('174','แกง',null,1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('175',' แกงป่า หมู, ไก่ , ปลาดุก',(select TOP 1 menu_id FROM so_menu WHERE menu_code='174'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('176',' แกงป่า นก,กบ,ปลาช่อน',(select TOP 1 menu_id FROM so_menu WHERE menu_code='174'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('177',' แกงป่า ทะเล, รวมมิตร',(select TOP 1 menu_id FROM so_menu WHERE menu_code='174'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('178',' แกงส้มชะอมใส่กุ้ง / ปลา',(select TOP 1 menu_id FROM so_menu WHERE menu_code='174'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('179',' แกงส้มผักรวมกุ้ง / ปลา',(select TOP 1 menu_id FROM so_menu WHERE menu_code='174'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('180',' แกงส้มปลาทอด',(select TOP 1 menu_id FROM so_menu WHERE menu_code='174'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('181',' แกงแพนงหมู, ไก่',(select TOP 1 menu_id FROM so_menu WHERE menu_code='174'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('182',' แกงเขียวหวาน หมู, ไก่',(select TOP 1 menu_id FROM so_menu WHERE menu_code='174'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('183','กับแกล้ม',null,1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('184','แหนมทรงเครื่อง',(select TOP 1 menu_id FROM so_menu WHERE menu_code='183'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('185','ไข่เยี่ยวม้าทรงเครื่อง',(select TOP 1 menu_id FROM so_menu WHERE menu_code='183'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('186','เครื่องดื่ม',null,1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('187','น้ำเปล่า',(select TOP 1 menu_id FROM so_menu WHERE menu_code='186'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('188','น้ำอัดลม',(select TOP 1 menu_id FROM so_menu WHERE menu_code='186'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('189','น้ำผมไม้',(select TOP 1 menu_id FROM so_menu WHERE menu_code='186'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())
, ('190','ชา',(select TOP 1 menu_id FROM so_menu WHERE menu_code='186'),1 ,'SYSTEM' ,GETDATE() ,'SYSTEM' ,GETDATE())





